version: '3.3'

services:

  simple_service:
    image: rexposadas/simple_service
    container_name: rexposadas_simple_service
    build:
      context: ./apps/lessons/
      dockerfile: simple_service/Dockerfile
    environment:
      GIN_MODE: release
    expose:
      - '8080'
    ports:
      - '8080:8080'
    entrypoint: ['/app/simple_service', '--port', '8080']

